services:
  proxy:
    container_name: ebooks-app-proxy
    image: traefik:v2.11
    command: --providers.docker
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  backend:
    container_name: ebooks-app-backend
    build:
      context: ./
      target: backend-dev
    develop:
      watch:
        - path: ./server/src
          action: sync
          target: /usr/local/app/src
        - path: ./server/package.json
          action: rebuild
    volumes:
      - backend_uploads:/usr/local/app/uploads
    depends_on:
      - mongo
    labels:
      traefik.http.routers.backend.rule: Host(`localhost`) && PathPrefix(`/api`)
      traefik.http.services.backend.loadbalancer.server.port: 5000

  client:
    container_name: ebooks-app-client
    build:
      context: ./
      target: client-dev
    develop:
      watch:
        - path: ./client/src
          action: sync
          target: /usr/local/app/src
        - path: ./client/package.json
          action: rebuild
    labels:
      traefik.http.routers.client.rule: Host(`localhost`)
      traefik.http.services.client.loadbalancer.server.port: 3000

  # ui-tests:
  #   image: mcr.microsoft.com/playwright:v1.41.0
  #   container_name: ui-tests
  #   build:
  #     context: ./
  #     target: ui-tests
  #   volumes:
  #     - ./ui-tests/playwright-report:/usr/local/app/playwright-report
  #   depends_on:
  #     - client
  #   command: ["xvfb-run", "npx", "playwright", "test", "--headed"]

  # ui-tests:
  #   image: mcr.microsoft.com/playwright:v1.41.0
  #   container_name: ui-tests
  #   build:
  #     context: ./
  #     target: ui-tests
  #   volumes:
  #     - ./client:/usr/local/app/client
  #     - ./client/playwright-report:/usr/local/app/playwright-report
  #   environment:
  #     - BASE_URL=http://client:3000
  #   depends_on:
  #     - client
  #     - backend
  #   command:
  #     [
  #       "xvfb-run",
  #       "npx",
  #       "playwright",
  #       "test",
  #       "--project=chromium",
  #       "--config=client/playwright.config.ts",
  #     ]

  ui-tests:
    # Remove this line as we're building the image from Dockerfile
    # image: mcr.microsoft.com/playwright:v1.41.0
    container_name: ui-tests
    build:
      context: ./
      target: ui-tests
    volumes:
      - ./client:/usr/local/app/client
      - ./client/playwright-report:/usr/local/app/playwright-report
    environment:
      - BASE_URL=http://client:3000
    depends_on:
      - client
      - backend
    command:
      [
        "xvfb-run",
        "npx",
        "playwright",
        "test",
        "--project=chromium",
        "--config=client/playwright.config.ts",
      ]

  mongo:
    image: mongo:8.0
    container_name: ebooks-app-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: ebooks-db
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js

volumes:
  mongodata:
    driver: local
  backend_uploads:
    driver: local
