version: "3.8"

services:
  mongo:
    image: mongo:8.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: ebooks-db
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js

volumes:
  mongodata:
    driver: local
