services:
  proxy:
    container_name: ebooks-app-proxy
    image: traefik:v2.11
    command: --providers.docker
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  backend:
    container_name: ebooks-app-backend
    build:
      context: ./
      target: backend-dev
    volumes:
      - backend_uploads:/usr/local/app/uploads
    depends_on:
      - mongo
    labels:
      traefik.http.routers.backend.rule: Host(`localhost`) && PathPrefix(`/api`)
      traefik.http.services.backend.loadbalancer.server.port: 5000

  client:
    container_name: ebooks-app-client
    build:
      context: ./
      target: client-dev
    depends_on:
      - backend
    labels:
      traefik.http.routers.client.rule: Host(`localhost`)
      traefik.http.services.client.loadbalancer.server.port: 3000

  ui-tests:
    container_name: ui-tests
    build:
      context: ./
      target: ui-tests
    volumes:
      - ./client:/usr/local/app/client
      - ./client/playwright-report:/usr/local/app/playwright-report
    environment:
      - BASE_URL=http://client:3000
    depends_on:
      - client
      - backend
    command:
      [
        "xvfb-run",
        "npx",
        "playwright",
        "test",
        "--project=chromium",
        "--config=client/playwright.config.ts",
      ]
    profiles: ["test"]

  mongo:
    image: mongo:8.0
    container_name: ebooks-app-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: ebooks-db
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js

volumes:
  mongodata:
    driver: local
  backend_uploads:
    driver: local
