export const genres = [
  "Fiction",
  "Non-Fiction",
  "Mystery",
  "Thriller",
  "Fantasy",
  "Science Fiction",
  "Romance",
  "Historical Fiction",
  "Biography",
  "Autobiography",
  "Self-Help",
  "Graphic Novel",
  "Horror",
  "Young Adult",
  "Children's Literature",
  "Poetry",
  "Drama",
  "Adventure",
  "Dystopian",
  "Classic",
  "Cooking",
  "Travel",
  "Health & Fitness",
  "Science",
  "Religion",
  "Philosophy",
  "Humor",
  "Business",
  "Technology",
  "Education",
  "True Crime",
  "Memoir",
  "Art",
  "Music",
  "Sports",
  "Parenting",
  "Politics",
  "Psychology",
  "Spirituality",
];
